### ISSUE TITLE
Add support for a QSPI enabled flash-driver for the RP2040 board

### ISSUE THREAD

**Issue by nihalpasham** [nihalpasham/rustBoot#19]
In order to port rustBoot to the `RP2040` board, we'll need to implement a flash-driver written in rust.

**Sub-tasks:**
- [ ] The flash driver must write and erase data-blocks from the device's external flash memory. 
- [ ] More specifically, the `RP2040` includes an Q-SPI flash chip, the flash driver must be a QSPI driver capable of performing `block write and erase` operations. 
- [ ] Finally, it must implement rustBoot's `FlashInterface` trait.

Additional notes:
- You only need to implement the methods (of `FlashInterface` trait), applicable to your board.

**Comment by abhishekdhamale** [comment]
Acknowledged

**Comment by sarath3192** [comment]
Acknowledged

**Comment by abhishekdhamale** [comment]
All sub-tasks are completed and PR #45 submitted.
