### ISSUE TITLE
Add a rust-based flash driver for STM32F334 dev-board

### ISSUE THREAD

**Issue by nihalpasham** [nihalpasham/rustBoot#20]
In order to port rustBoot to the `STM32F334` board, we'll need to implement a flash-driver written in rust. 

**Sub-tasks:**
- [ ] The flash driver should support lock and unlock flash operations. 
- [ ] The flash driver must read, write and erase data-blocks from the device's internal flash memory.
- [ ] Finally, it must implement rustBoot's `FlashInterface` trait. 

Additional notes: 
- You only need to implement the methods (of `FlashInterface` trait), applicable to your board.

**Comment by sarath3192** [comment]
Acknowledged

**Comment by imrank03** [comment]
Acknowledged.
