### ISSUE TITLE
Add a rust-based NVMC driver for the STM32F446RE board

### ISSUE THREAD

**Issue by nihalpasham** [nihalpasham/rustBoot#21]
In order to port rustBoot to the `STM32F446RE` board, we'll need to implement a flash-driver written in rust. 

**Sub-tasks:**
- [x] The flash driver should support lock and unlock flash operations. 
- [x] The flash driver must read, write and erase data-blocks from the device's internal flash memory.
- [x] Finally, it must implement rustBoot's `FlashInterface` trait. 

Additional notes: 
- You only need to implement the methods (of `FlashInterface` trait), applicable to your board.

**Comment by yashwanthsinghm** [comment]
Acknowledged

**Comment by Strange21** [comment]
Acknowledged

**Comment by Strange21** [comment]
The driver is Implemented. 
Boot-firmware and Updated firmware is generated.
Signed both the images and flashed on to the controller.

**Comment by Strange21** [comment]
However the it seems that the firmware has not been started. Need to debug the problem using some debugging technique.
