### ISSUE TITLE
Add rust-based flash driver for the "STM32H723ZG" board

### ISSUE THREAD

**Issue by imrank03** [nihalpasham/rustBoot#26]
In order to port rustBoot to the `STM32H723ZG` board, we'll need to implement a flash-driver written in rust.

**Sub-tasks:**
- [x] The flash driver should support lock and unlock flash operations.
- [x]   The flash driver must write and erase data-blocks from the device's internal flash memory.
- [x]   Finally, it must implement rustBoot's `FlashInterface` trait.

Additional notes:
- You only need to implement the methods (of `FlashInterface` trait), applicable to your board.
