### ISSUE TITLE
Firmware distribution platform using OCKAM Crate

### ISSUE THREAD

**Issue by sarath3192** [nihalpasham/rustBoot#70]
Develop a firmware distribution application using Ockam Crate

**sub-tasks**

- [ ] Communicate text messages over Local network
- [ ] Communicate text messages over internet
- [ ] Distribute firmware files over internet

**Comment by sarath3192** [comment]
Add support for Embassy executor for Ockam on Stm boards.
